# Generated by Django 2.1.7 on 2019-04-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='accountuser',
            name='password',
            field=models.CharField(default=111, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountuser',
            name='username',
            field=models.CharField(default=222, max_length=120),
            preserve_default=False,
        ),
    ]
