# Generated by Django 2.1.7 on 2019-04-23 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190423_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='accountuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='accountuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+381...'. Up to 15 digits allowed.", regex='^\\+\\d{8,15}$')]),
        ),
    ]
