# Generated by Django 2.1.7 on 2019-04-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190423_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='location',
            field=models.CharField(max_length=60),
        ),
    ]
